services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  web:
    build: .
    command: gunicorn anno.wsgi -b :8530
    volumes:
      - .${MEDIA_VOLUME}:/code${MEDIA_VOLUME}
      - ./static:/code/static
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - STATIC_ROOT=/code/static
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data:
    driver: local