# Generated by Django 5.0.6 on 2024-05-22 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0004_dataset_name_dataset_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 16, 2, 37, 299958, tzinfo=datetime.timezone.utc), verbose_name='date added'),
        ),
    ]
