# Generated by Django 5.0.6 on 2024-05-22 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0005_record_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 17, 17, 9, 28152, tzinfo=datetime.timezone.utc), verbose_name='date added'),
        ),
    ]
