# Generated by Django 5.0.6 on 2024-05-23 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0006_record_score_alter_record_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tar_file', models.CharField(max_length=50)),
                ('audio_file', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
    ]
