# Generated by Django 5.0.6 on 2024-05-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0007_archivemap_alter_record_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivemap',
            name='tar_file',
            field=models.SmallIntegerField(),
        ),
    ]
