# Generated by Django 5.0.6 on 2024-05-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0008_alter_archivemap_tar_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asrann.dataset')),
            ],
        ),
    ]
