# Generated by Django 5.0.6 on 2024-05-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0009_activedataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay', models.BooleanField(default=True)),
            ],
        ),
    ]
