# Generated by Django 5.0.6 on 2024-07-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0012_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
