# Generated by Django 5.0.6 on 2024-07-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0013_alter_vote_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seen',
        ),
    ]
