# Generated by Django 5.0.6 on 2024-07-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0015_record_tar_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveMap',
        ),
    ]
