# Generated by Django 5.0.6 on 2024-07-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0016_delete_archivemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_tested',
            field=models.BooleanField(default=False),
        ),
    ]
