# Generated by Django 5.0.6 on 2024-07-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrann', '0017_customuser_user_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passed_score',
            field=models.IntegerField(default=10),
        ),
    ]
